spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # MySQL setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://asrai-app-database.cwk2ukisdzzj.ap-northeast-2.rds.amazonaws.com:13386/zoosum?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: adminasrai
    password: joinit!!asrai

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      #        default_batch_fetch_size: 1000
      open-in-view: true

server:
  port: 5000
  servlet:
    context-path: /api

logging:
  level:
    com.com.vegetable: debug

